/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as R404RouteImport } from './routes/404'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SuperAdminUsersRouteImport } from './routes/super-admin/users'
import { Route as SuperAdminTicketsRouteImport } from './routes/super-admin/tickets'
import { Route as SuperAdminStaffRouteImport } from './routes/super-admin/staff'
import { Route as SuperAdminSettingsRouteImport } from './routes/super-admin/settings'
import { Route as SuperAdminProfileRouteImport } from './routes/super-admin/profile'
import { Route as SuperAdminDashboardRouteImport } from './routes/super-admin/dashboard'
import { Route as SuperAdminLayoutRouteImport } from './routes/super-admin/_layout'
import { Route as StudentTicketsRouteImport } from './routes/student/tickets'
import { Route as StudentProfileRouteImport } from './routes/student/profile'
import { Route as StudentDashboardRouteImport } from './routes/student/dashboard'
import { Route as StudentLayoutRouteImport } from './routes/student/_layout'
import { Route as StaffTicketsRouteImport } from './routes/staff/tickets'
import { Route as StaffProfileRouteImport } from './routes/staff/profile'
import { Route as StaffDashboardRouteImport } from './routes/staff/dashboard'
import { Route as StaffAssignedTicketsRouteImport } from './routes/staff/assigned-tickets'
import { Route as StaffLayoutRouteImport } from './routes/staff/_layout'
import { Route as IctTicketsRouteImport } from './routes/ict/tickets'
import { Route as IctProfileRouteImport } from './routes/ict/profile'
import { Route as IctNotificationsRouteImport } from './routes/ict/notifications'
import { Route as IctDashboardRouteImport } from './routes/ict/dashboard'
import { Route as IctAssignedTicketsRouteImport } from './routes/ict/assigned-tickets'
import { Route as IctLayoutRouteImport } from './routes/ict/_layout'
import { Route as StudentTicketsIndexRouteImport } from './routes/student/tickets/index'
import { Route as SuperAdminTicketTicketIdRouteImport } from './routes/super-admin/ticket/$ticketId'
import { Route as StudentTicketsNewRouteImport } from './routes/student/tickets/new'
import { Route as StudentTicketsTicketIdRouteImport } from './routes/student/tickets/$ticketId'
import { Route as StaffTicketsAssignedRouteImport } from './routes/staff/tickets/assigned'
import { Route as StaffTicketTicketIdRouteImport } from './routes/staff/ticket/$ticketId'
import { Route as IctTicketsAssignedRouteImport } from './routes/ict/tickets/assigned'
import { Route as IctTicketTicketIdRouteImport } from './routes/ict/ticket/$ticketId'

const SuperAdminRouteImport = createFileRoute('/super-admin')()
const StudentRouteImport = createFileRoute('/student')()
const StaffRouteImport = createFileRoute('/staff')()
const IctRouteImport = createFileRoute('/ict')()

const SuperAdminRoute = SuperAdminRouteImport.update({
  id: '/super-admin',
  path: '/super-admin',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentRoute = StudentRouteImport.update({
  id: '/student',
  path: '/student',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffRoute = StaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => rootRouteImport,
} as any)
const IctRoute = IctRouteImport.update({
  id: '/ict',
  path: '/ict',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const R404Route = R404RouteImport.update({
  id: '/404',
  path: '/404',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperAdminUsersRoute = SuperAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => SuperAdminRoute,
} as any)
const SuperAdminTicketsRoute = SuperAdminTicketsRouteImport.update({
  id: '/tickets',
  path: '/tickets',
  getParentRoute: () => SuperAdminRoute,
} as any)
const SuperAdminStaffRoute = SuperAdminStaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => SuperAdminRoute,
} as any)
const SuperAdminSettingsRoute = SuperAdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => SuperAdminRoute,
} as any)
const SuperAdminProfileRoute = SuperAdminProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => SuperAdminRoute,
} as any)
const SuperAdminDashboardRoute = SuperAdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => SuperAdminRoute,
} as any)
const SuperAdminLayoutRoute = SuperAdminLayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => SuperAdminRoute,
} as any)
const StudentTicketsRoute = StudentTicketsRouteImport.update({
  id: '/tickets',
  path: '/tickets',
  getParentRoute: () => StudentRoute,
} as any)
const StudentProfileRoute = StudentProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => StudentRoute,
} as any)
const StudentDashboardRoute = StudentDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => StudentRoute,
} as any)
const StudentLayoutRoute = StudentLayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => StudentRoute,
} as any)
const StaffTicketsRoute = StaffTicketsRouteImport.update({
  id: '/tickets',
  path: '/tickets',
  getParentRoute: () => StaffRoute,
} as any)
const StaffProfileRoute = StaffProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => StaffRoute,
} as any)
const StaffDashboardRoute = StaffDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => StaffRoute,
} as any)
const StaffAssignedTicketsRoute = StaffAssignedTicketsRouteImport.update({
  id: '/assigned-tickets',
  path: '/assigned-tickets',
  getParentRoute: () => StaffRoute,
} as any)
const StaffLayoutRoute = StaffLayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => StaffRoute,
} as any)
const IctTicketsRoute = IctTicketsRouteImport.update({
  id: '/tickets',
  path: '/tickets',
  getParentRoute: () => IctRoute,
} as any)
const IctProfileRoute = IctProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => IctRoute,
} as any)
const IctNotificationsRoute = IctNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => IctRoute,
} as any)
const IctDashboardRoute = IctDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => IctRoute,
} as any)
const IctAssignedTicketsRoute = IctAssignedTicketsRouteImport.update({
  id: '/assigned-tickets',
  path: '/assigned-tickets',
  getParentRoute: () => IctRoute,
} as any)
const IctLayoutRoute = IctLayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => IctRoute,
} as any)
const StudentTicketsIndexRoute = StudentTicketsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StudentTicketsRoute,
} as any)
const SuperAdminTicketTicketIdRoute =
  SuperAdminTicketTicketIdRouteImport.update({
    id: '/ticket/$ticketId',
    path: '/ticket/$ticketId',
    getParentRoute: () => SuperAdminRoute,
  } as any)
const StudentTicketsNewRoute = StudentTicketsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => StudentTicketsRoute,
} as any)
const StudentTicketsTicketIdRoute = StudentTicketsTicketIdRouteImport.update({
  id: '/$ticketId',
  path: '/$ticketId',
  getParentRoute: () => StudentTicketsRoute,
} as any)
const StaffTicketsAssignedRoute = StaffTicketsAssignedRouteImport.update({
  id: '/assigned',
  path: '/assigned',
  getParentRoute: () => StaffTicketsRoute,
} as any)
const StaffTicketTicketIdRoute = StaffTicketTicketIdRouteImport.update({
  id: '/ticket/$ticketId',
  path: '/ticket/$ticketId',
  getParentRoute: () => StaffRoute,
} as any)
const IctTicketsAssignedRoute = IctTicketsAssignedRouteImport.update({
  id: '/assigned',
  path: '/assigned',
  getParentRoute: () => IctTicketsRoute,
} as any)
const IctTicketTicketIdRoute = IctTicketTicketIdRouteImport.update({
  id: '/ticket/$ticketId',
  path: '/ticket/$ticketId',
  getParentRoute: () => IctRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/404': typeof R404Route
  '/login': typeof LoginRoute
  '/ict': typeof IctLayoutRoute
  '/ict/assigned-tickets': typeof IctAssignedTicketsRoute
  '/ict/dashboard': typeof IctDashboardRoute
  '/ict/notifications': typeof IctNotificationsRoute
  '/ict/profile': typeof IctProfileRoute
  '/ict/tickets': typeof IctTicketsRouteWithChildren
  '/staff': typeof StaffLayoutRoute
  '/staff/assigned-tickets': typeof StaffAssignedTicketsRoute
  '/staff/dashboard': typeof StaffDashboardRoute
  '/staff/profile': typeof StaffProfileRoute
  '/staff/tickets': typeof StaffTicketsRouteWithChildren
  '/student': typeof StudentLayoutRoute
  '/student/dashboard': typeof StudentDashboardRoute
  '/student/profile': typeof StudentProfileRoute
  '/student/tickets': typeof StudentTicketsRouteWithChildren
  '/super-admin': typeof SuperAdminLayoutRoute
  '/super-admin/dashboard': typeof SuperAdminDashboardRoute
  '/super-admin/profile': typeof SuperAdminProfileRoute
  '/super-admin/settings': typeof SuperAdminSettingsRoute
  '/super-admin/staff': typeof SuperAdminStaffRoute
  '/super-admin/tickets': typeof SuperAdminTicketsRoute
  '/super-admin/users': typeof SuperAdminUsersRoute
  '/ict/ticket/$ticketId': typeof IctTicketTicketIdRoute
  '/ict/tickets/assigned': typeof IctTicketsAssignedRoute
  '/staff/ticket/$ticketId': typeof StaffTicketTicketIdRoute
  '/staff/tickets/assigned': typeof StaffTicketsAssignedRoute
  '/student/tickets/$ticketId': typeof StudentTicketsTicketIdRoute
  '/student/tickets/new': typeof StudentTicketsNewRoute
  '/super-admin/ticket/$ticketId': typeof SuperAdminTicketTicketIdRoute
  '/student/tickets/': typeof StudentTicketsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/404': typeof R404Route
  '/login': typeof LoginRoute
  '/ict': typeof IctLayoutRoute
  '/ict/assigned-tickets': typeof IctAssignedTicketsRoute
  '/ict/dashboard': typeof IctDashboardRoute
  '/ict/notifications': typeof IctNotificationsRoute
  '/ict/profile': typeof IctProfileRoute
  '/ict/tickets': typeof IctTicketsRouteWithChildren
  '/staff': typeof StaffLayoutRoute
  '/staff/assigned-tickets': typeof StaffAssignedTicketsRoute
  '/staff/dashboard': typeof StaffDashboardRoute
  '/staff/profile': typeof StaffProfileRoute
  '/staff/tickets': typeof StaffTicketsRouteWithChildren
  '/student': typeof StudentLayoutRoute
  '/student/dashboard': typeof StudentDashboardRoute
  '/student/profile': typeof StudentProfileRoute
  '/super-admin': typeof SuperAdminLayoutRoute
  '/super-admin/dashboard': typeof SuperAdminDashboardRoute
  '/super-admin/profile': typeof SuperAdminProfileRoute
  '/super-admin/settings': typeof SuperAdminSettingsRoute
  '/super-admin/staff': typeof SuperAdminStaffRoute
  '/super-admin/tickets': typeof SuperAdminTicketsRoute
  '/super-admin/users': typeof SuperAdminUsersRoute
  '/ict/ticket/$ticketId': typeof IctTicketTicketIdRoute
  '/ict/tickets/assigned': typeof IctTicketsAssignedRoute
  '/staff/ticket/$ticketId': typeof StaffTicketTicketIdRoute
  '/staff/tickets/assigned': typeof StaffTicketsAssignedRoute
  '/student/tickets/$ticketId': typeof StudentTicketsTicketIdRoute
  '/student/tickets/new': typeof StudentTicketsNewRoute
  '/super-admin/ticket/$ticketId': typeof SuperAdminTicketTicketIdRoute
  '/student/tickets': typeof StudentTicketsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/404': typeof R404Route
  '/login': typeof LoginRoute
  '/ict': typeof IctRouteWithChildren
  '/ict/_layout': typeof IctLayoutRoute
  '/ict/assigned-tickets': typeof IctAssignedTicketsRoute
  '/ict/dashboard': typeof IctDashboardRoute
  '/ict/notifications': typeof IctNotificationsRoute
  '/ict/profile': typeof IctProfileRoute
  '/ict/tickets': typeof IctTicketsRouteWithChildren
  '/staff': typeof StaffRouteWithChildren
  '/staff/_layout': typeof StaffLayoutRoute
  '/staff/assigned-tickets': typeof StaffAssignedTicketsRoute
  '/staff/dashboard': typeof StaffDashboardRoute
  '/staff/profile': typeof StaffProfileRoute
  '/staff/tickets': typeof StaffTicketsRouteWithChildren
  '/student': typeof StudentRouteWithChildren
  '/student/_layout': typeof StudentLayoutRoute
  '/student/dashboard': typeof StudentDashboardRoute
  '/student/profile': typeof StudentProfileRoute
  '/student/tickets': typeof StudentTicketsRouteWithChildren
  '/super-admin': typeof SuperAdminRouteWithChildren
  '/super-admin/_layout': typeof SuperAdminLayoutRoute
  '/super-admin/dashboard': typeof SuperAdminDashboardRoute
  '/super-admin/profile': typeof SuperAdminProfileRoute
  '/super-admin/settings': typeof SuperAdminSettingsRoute
  '/super-admin/staff': typeof SuperAdminStaffRoute
  '/super-admin/tickets': typeof SuperAdminTicketsRoute
  '/super-admin/users': typeof SuperAdminUsersRoute
  '/ict/ticket/$ticketId': typeof IctTicketTicketIdRoute
  '/ict/tickets/assigned': typeof IctTicketsAssignedRoute
  '/staff/ticket/$ticketId': typeof StaffTicketTicketIdRoute
  '/staff/tickets/assigned': typeof StaffTicketsAssignedRoute
  '/student/tickets/$ticketId': typeof StudentTicketsTicketIdRoute
  '/student/tickets/new': typeof StudentTicketsNewRoute
  '/super-admin/ticket/$ticketId': typeof SuperAdminTicketTicketIdRoute
  '/student/tickets/': typeof StudentTicketsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/404'
    | '/login'
    | '/ict'
    | '/ict/assigned-tickets'
    | '/ict/dashboard'
    | '/ict/notifications'
    | '/ict/profile'
    | '/ict/tickets'
    | '/staff'
    | '/staff/assigned-tickets'
    | '/staff/dashboard'
    | '/staff/profile'
    | '/staff/tickets'
    | '/student'
    | '/student/dashboard'
    | '/student/profile'
    | '/student/tickets'
    | '/super-admin'
    | '/super-admin/dashboard'
    | '/super-admin/profile'
    | '/super-admin/settings'
    | '/super-admin/staff'
    | '/super-admin/tickets'
    | '/super-admin/users'
    | '/ict/ticket/$ticketId'
    | '/ict/tickets/assigned'
    | '/staff/ticket/$ticketId'
    | '/staff/tickets/assigned'
    | '/student/tickets/$ticketId'
    | '/student/tickets/new'
    | '/super-admin/ticket/$ticketId'
    | '/student/tickets/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/404'
    | '/login'
    | '/ict'
    | '/ict/assigned-tickets'
    | '/ict/dashboard'
    | '/ict/notifications'
    | '/ict/profile'
    | '/ict/tickets'
    | '/staff'
    | '/staff/assigned-tickets'
    | '/staff/dashboard'
    | '/staff/profile'
    | '/staff/tickets'
    | '/student'
    | '/student/dashboard'
    | '/student/profile'
    | '/super-admin'
    | '/super-admin/dashboard'
    | '/super-admin/profile'
    | '/super-admin/settings'
    | '/super-admin/staff'
    | '/super-admin/tickets'
    | '/super-admin/users'
    | '/ict/ticket/$ticketId'
    | '/ict/tickets/assigned'
    | '/staff/ticket/$ticketId'
    | '/staff/tickets/assigned'
    | '/student/tickets/$ticketId'
    | '/student/tickets/new'
    | '/super-admin/ticket/$ticketId'
    | '/student/tickets'
  id:
    | '__root__'
    | '/'
    | '/404'
    | '/login'
    | '/ict'
    | '/ict/_layout'
    | '/ict/assigned-tickets'
    | '/ict/dashboard'
    | '/ict/notifications'
    | '/ict/profile'
    | '/ict/tickets'
    | '/staff'
    | '/staff/_layout'
    | '/staff/assigned-tickets'
    | '/staff/dashboard'
    | '/staff/profile'
    | '/staff/tickets'
    | '/student'
    | '/student/_layout'
    | '/student/dashboard'
    | '/student/profile'
    | '/student/tickets'
    | '/super-admin'
    | '/super-admin/_layout'
    | '/super-admin/dashboard'
    | '/super-admin/profile'
    | '/super-admin/settings'
    | '/super-admin/staff'
    | '/super-admin/tickets'
    | '/super-admin/users'
    | '/ict/ticket/$ticketId'
    | '/ict/tickets/assigned'
    | '/staff/ticket/$ticketId'
    | '/staff/tickets/assigned'
    | '/student/tickets/$ticketId'
    | '/student/tickets/new'
    | '/super-admin/ticket/$ticketId'
    | '/student/tickets/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  R404Route: typeof R404Route
  LoginRoute: typeof LoginRoute
  IctRoute: typeof IctRouteWithChildren
  StaffRoute: typeof StaffRouteWithChildren
  StudentRoute: typeof StudentRouteWithChildren
  SuperAdminRoute: typeof SuperAdminRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/super-admin': {
      id: '/super-admin'
      path: '/super-admin'
      fullPath: '/super-admin'
      preLoaderRoute: typeof SuperAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student': {
      id: '/student'
      path: '/student'
      fullPath: '/student'
      preLoaderRoute: typeof StudentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff': {
      id: '/staff'
      path: '/staff'
      fullPath: '/staff'
      preLoaderRoute: typeof StaffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ict': {
      id: '/ict'
      path: '/ict'
      fullPath: '/ict'
      preLoaderRoute: typeof IctRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/404': {
      id: '/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof R404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/super-admin/users': {
      id: '/super-admin/users'
      path: '/users'
      fullPath: '/super-admin/users'
      preLoaderRoute: typeof SuperAdminUsersRouteImport
      parentRoute: typeof SuperAdminRoute
    }
    '/super-admin/tickets': {
      id: '/super-admin/tickets'
      path: '/tickets'
      fullPath: '/super-admin/tickets'
      preLoaderRoute: typeof SuperAdminTicketsRouteImport
      parentRoute: typeof SuperAdminRoute
    }
    '/super-admin/staff': {
      id: '/super-admin/staff'
      path: '/staff'
      fullPath: '/super-admin/staff'
      preLoaderRoute: typeof SuperAdminStaffRouteImport
      parentRoute: typeof SuperAdminRoute
    }
    '/super-admin/settings': {
      id: '/super-admin/settings'
      path: '/settings'
      fullPath: '/super-admin/settings'
      preLoaderRoute: typeof SuperAdminSettingsRouteImport
      parentRoute: typeof SuperAdminRoute
    }
    '/super-admin/profile': {
      id: '/super-admin/profile'
      path: '/profile'
      fullPath: '/super-admin/profile'
      preLoaderRoute: typeof SuperAdminProfileRouteImport
      parentRoute: typeof SuperAdminRoute
    }
    '/super-admin/dashboard': {
      id: '/super-admin/dashboard'
      path: '/dashboard'
      fullPath: '/super-admin/dashboard'
      preLoaderRoute: typeof SuperAdminDashboardRouteImport
      parentRoute: typeof SuperAdminRoute
    }
    '/super-admin/_layout': {
      id: '/super-admin/_layout'
      path: '/super-admin'
      fullPath: '/super-admin'
      preLoaderRoute: typeof SuperAdminLayoutRouteImport
      parentRoute: typeof SuperAdminRoute
    }
    '/student/tickets': {
      id: '/student/tickets'
      path: '/tickets'
      fullPath: '/student/tickets'
      preLoaderRoute: typeof StudentTicketsRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/profile': {
      id: '/student/profile'
      path: '/profile'
      fullPath: '/student/profile'
      preLoaderRoute: typeof StudentProfileRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/dashboard': {
      id: '/student/dashboard'
      path: '/dashboard'
      fullPath: '/student/dashboard'
      preLoaderRoute: typeof StudentDashboardRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/_layout': {
      id: '/student/_layout'
      path: '/student'
      fullPath: '/student'
      preLoaderRoute: typeof StudentLayoutRouteImport
      parentRoute: typeof StudentRoute
    }
    '/staff/tickets': {
      id: '/staff/tickets'
      path: '/tickets'
      fullPath: '/staff/tickets'
      preLoaderRoute: typeof StaffTicketsRouteImport
      parentRoute: typeof StaffRoute
    }
    '/staff/profile': {
      id: '/staff/profile'
      path: '/profile'
      fullPath: '/staff/profile'
      preLoaderRoute: typeof StaffProfileRouteImport
      parentRoute: typeof StaffRoute
    }
    '/staff/dashboard': {
      id: '/staff/dashboard'
      path: '/dashboard'
      fullPath: '/staff/dashboard'
      preLoaderRoute: typeof StaffDashboardRouteImport
      parentRoute: typeof StaffRoute
    }
    '/staff/assigned-tickets': {
      id: '/staff/assigned-tickets'
      path: '/assigned-tickets'
      fullPath: '/staff/assigned-tickets'
      preLoaderRoute: typeof StaffAssignedTicketsRouteImport
      parentRoute: typeof StaffRoute
    }
    '/staff/_layout': {
      id: '/staff/_layout'
      path: '/staff'
      fullPath: '/staff'
      preLoaderRoute: typeof StaffLayoutRouteImport
      parentRoute: typeof StaffRoute
    }
    '/ict/tickets': {
      id: '/ict/tickets'
      path: '/tickets'
      fullPath: '/ict/tickets'
      preLoaderRoute: typeof IctTicketsRouteImport
      parentRoute: typeof IctRoute
    }
    '/ict/profile': {
      id: '/ict/profile'
      path: '/profile'
      fullPath: '/ict/profile'
      preLoaderRoute: typeof IctProfileRouteImport
      parentRoute: typeof IctRoute
    }
    '/ict/notifications': {
      id: '/ict/notifications'
      path: '/notifications'
      fullPath: '/ict/notifications'
      preLoaderRoute: typeof IctNotificationsRouteImport
      parentRoute: typeof IctRoute
    }
    '/ict/dashboard': {
      id: '/ict/dashboard'
      path: '/dashboard'
      fullPath: '/ict/dashboard'
      preLoaderRoute: typeof IctDashboardRouteImport
      parentRoute: typeof IctRoute
    }
    '/ict/assigned-tickets': {
      id: '/ict/assigned-tickets'
      path: '/assigned-tickets'
      fullPath: '/ict/assigned-tickets'
      preLoaderRoute: typeof IctAssignedTicketsRouteImport
      parentRoute: typeof IctRoute
    }
    '/ict/_layout': {
      id: '/ict/_layout'
      path: '/ict'
      fullPath: '/ict'
      preLoaderRoute: typeof IctLayoutRouteImport
      parentRoute: typeof IctRoute
    }
    '/student/tickets/': {
      id: '/student/tickets/'
      path: '/'
      fullPath: '/student/tickets/'
      preLoaderRoute: typeof StudentTicketsIndexRouteImport
      parentRoute: typeof StudentTicketsRoute
    }
    '/super-admin/ticket/$ticketId': {
      id: '/super-admin/ticket/$ticketId'
      path: '/ticket/$ticketId'
      fullPath: '/super-admin/ticket/$ticketId'
      preLoaderRoute: typeof SuperAdminTicketTicketIdRouteImport
      parentRoute: typeof SuperAdminRoute
    }
    '/student/tickets/new': {
      id: '/student/tickets/new'
      path: '/new'
      fullPath: '/student/tickets/new'
      preLoaderRoute: typeof StudentTicketsNewRouteImport
      parentRoute: typeof StudentTicketsRoute
    }
    '/student/tickets/$ticketId': {
      id: '/student/tickets/$ticketId'
      path: '/$ticketId'
      fullPath: '/student/tickets/$ticketId'
      preLoaderRoute: typeof StudentTicketsTicketIdRouteImport
      parentRoute: typeof StudentTicketsRoute
    }
    '/staff/tickets/assigned': {
      id: '/staff/tickets/assigned'
      path: '/assigned'
      fullPath: '/staff/tickets/assigned'
      preLoaderRoute: typeof StaffTicketsAssignedRouteImport
      parentRoute: typeof StaffTicketsRoute
    }
    '/staff/ticket/$ticketId': {
      id: '/staff/ticket/$ticketId'
      path: '/ticket/$ticketId'
      fullPath: '/staff/ticket/$ticketId'
      preLoaderRoute: typeof StaffTicketTicketIdRouteImport
      parentRoute: typeof StaffRoute
    }
    '/ict/tickets/assigned': {
      id: '/ict/tickets/assigned'
      path: '/assigned'
      fullPath: '/ict/tickets/assigned'
      preLoaderRoute: typeof IctTicketsAssignedRouteImport
      parentRoute: typeof IctTicketsRoute
    }
    '/ict/ticket/$ticketId': {
      id: '/ict/ticket/$ticketId'
      path: '/ticket/$ticketId'
      fullPath: '/ict/ticket/$ticketId'
      preLoaderRoute: typeof IctTicketTicketIdRouteImport
      parentRoute: typeof IctRoute
    }
  }
}

interface IctTicketsRouteChildren {
  IctTicketsAssignedRoute: typeof IctTicketsAssignedRoute
}

const IctTicketsRouteChildren: IctTicketsRouteChildren = {
  IctTicketsAssignedRoute: IctTicketsAssignedRoute,
}

const IctTicketsRouteWithChildren = IctTicketsRoute._addFileChildren(
  IctTicketsRouteChildren,
)

interface IctRouteChildren {
  IctLayoutRoute: typeof IctLayoutRoute
  IctAssignedTicketsRoute: typeof IctAssignedTicketsRoute
  IctDashboardRoute: typeof IctDashboardRoute
  IctNotificationsRoute: typeof IctNotificationsRoute
  IctProfileRoute: typeof IctProfileRoute
  IctTicketsRoute: typeof IctTicketsRouteWithChildren
  IctTicketTicketIdRoute: typeof IctTicketTicketIdRoute
}

const IctRouteChildren: IctRouteChildren = {
  IctLayoutRoute: IctLayoutRoute,
  IctAssignedTicketsRoute: IctAssignedTicketsRoute,
  IctDashboardRoute: IctDashboardRoute,
  IctNotificationsRoute: IctNotificationsRoute,
  IctProfileRoute: IctProfileRoute,
  IctTicketsRoute: IctTicketsRouteWithChildren,
  IctTicketTicketIdRoute: IctTicketTicketIdRoute,
}

const IctRouteWithChildren = IctRoute._addFileChildren(IctRouteChildren)

interface StaffTicketsRouteChildren {
  StaffTicketsAssignedRoute: typeof StaffTicketsAssignedRoute
}

const StaffTicketsRouteChildren: StaffTicketsRouteChildren = {
  StaffTicketsAssignedRoute: StaffTicketsAssignedRoute,
}

const StaffTicketsRouteWithChildren = StaffTicketsRoute._addFileChildren(
  StaffTicketsRouteChildren,
)

interface StaffRouteChildren {
  StaffLayoutRoute: typeof StaffLayoutRoute
  StaffAssignedTicketsRoute: typeof StaffAssignedTicketsRoute
  StaffDashboardRoute: typeof StaffDashboardRoute
  StaffProfileRoute: typeof StaffProfileRoute
  StaffTicketsRoute: typeof StaffTicketsRouteWithChildren
  StaffTicketTicketIdRoute: typeof StaffTicketTicketIdRoute
}

const StaffRouteChildren: StaffRouteChildren = {
  StaffLayoutRoute: StaffLayoutRoute,
  StaffAssignedTicketsRoute: StaffAssignedTicketsRoute,
  StaffDashboardRoute: StaffDashboardRoute,
  StaffProfileRoute: StaffProfileRoute,
  StaffTicketsRoute: StaffTicketsRouteWithChildren,
  StaffTicketTicketIdRoute: StaffTicketTicketIdRoute,
}

const StaffRouteWithChildren = StaffRoute._addFileChildren(StaffRouteChildren)

interface StudentTicketsRouteChildren {
  StudentTicketsTicketIdRoute: typeof StudentTicketsTicketIdRoute
  StudentTicketsNewRoute: typeof StudentTicketsNewRoute
  StudentTicketsIndexRoute: typeof StudentTicketsIndexRoute
}

const StudentTicketsRouteChildren: StudentTicketsRouteChildren = {
  StudentTicketsTicketIdRoute: StudentTicketsTicketIdRoute,
  StudentTicketsNewRoute: StudentTicketsNewRoute,
  StudentTicketsIndexRoute: StudentTicketsIndexRoute,
}

const StudentTicketsRouteWithChildren = StudentTicketsRoute._addFileChildren(
  StudentTicketsRouteChildren,
)

interface StudentRouteChildren {
  StudentLayoutRoute: typeof StudentLayoutRoute
  StudentDashboardRoute: typeof StudentDashboardRoute
  StudentProfileRoute: typeof StudentProfileRoute
  StudentTicketsRoute: typeof StudentTicketsRouteWithChildren
}

const StudentRouteChildren: StudentRouteChildren = {
  StudentLayoutRoute: StudentLayoutRoute,
  StudentDashboardRoute: StudentDashboardRoute,
  StudentProfileRoute: StudentProfileRoute,
  StudentTicketsRoute: StudentTicketsRouteWithChildren,
}

const StudentRouteWithChildren =
  StudentRoute._addFileChildren(StudentRouteChildren)

interface SuperAdminRouteChildren {
  SuperAdminLayoutRoute: typeof SuperAdminLayoutRoute
  SuperAdminDashboardRoute: typeof SuperAdminDashboardRoute
  SuperAdminProfileRoute: typeof SuperAdminProfileRoute
  SuperAdminSettingsRoute: typeof SuperAdminSettingsRoute
  SuperAdminStaffRoute: typeof SuperAdminStaffRoute
  SuperAdminTicketsRoute: typeof SuperAdminTicketsRoute
  SuperAdminUsersRoute: typeof SuperAdminUsersRoute
  SuperAdminTicketTicketIdRoute: typeof SuperAdminTicketTicketIdRoute
}

const SuperAdminRouteChildren: SuperAdminRouteChildren = {
  SuperAdminLayoutRoute: SuperAdminLayoutRoute,
  SuperAdminDashboardRoute: SuperAdminDashboardRoute,
  SuperAdminProfileRoute: SuperAdminProfileRoute,
  SuperAdminSettingsRoute: SuperAdminSettingsRoute,
  SuperAdminStaffRoute: SuperAdminStaffRoute,
  SuperAdminTicketsRoute: SuperAdminTicketsRoute,
  SuperAdminUsersRoute: SuperAdminUsersRoute,
  SuperAdminTicketTicketIdRoute: SuperAdminTicketTicketIdRoute,
}

const SuperAdminRouteWithChildren = SuperAdminRoute._addFileChildren(
  SuperAdminRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  R404Route: R404Route,
  LoginRoute: LoginRoute,
  IctRoute: IctRouteWithChildren,
  StaffRoute: StaffRouteWithChildren,
  StudentRoute: StudentRouteWithChildren,
  SuperAdminRoute: SuperAdminRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
